<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Cheques Report</title>
    <style>
        body {
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        .text-center {
            text-align: center;
        }

        .title {
            font-weight: bold;
            font-size: 24px;
            text-transform: uppercase;
            font-family: serif;
        }

        .subtitle {
            font-size: 16px;
            text-transform: uppercase;
            font-family: serif;
        }

        .logo {
            width: 70%;
            height: auto;
        }

        .no-border {
            border: none !important;
        }

        th,
        td {
            border: 1px solid #000000;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .text-muted {
            color: #6c757d !important;
            font-size: 8px;
        }
    </style>
</head>

<body>
    <table>
        <tr>
            <td style="width: 30%; text-align: center;" class="no-border">
                <img src="./images/CSWDO.webp" alt="" class="logo">
            </td>
            <td class="no-border">
                <h1 class="title text-center">Taguig City CSWDO</h1>
                <p class="subtitle text-center" style="font-weight: bold;">Funeral Assistance</p>
                <h2 class="text-center" style="font-family: serif; text-transform: uppercase;">Checks Report</h2>
                <p class="text-center" style="font-family: serif;">
                    {{ \Carbon\Carbon::parse($startDate)->format('F d, Y') }} to
                    {{ \Carbon\Carbon::parse($endDate)->format('F d, Y') }}</p>
            </td>
            <td style="width: 30%; text-align: center;" class="no-border">
                <img src="./images/city_logo.webp" alt="" class="logo">
            </td>
        </tr>
    </table>
    <h2>Charts</h2>
    @if (!empty($charts))
        <table class="no-border" style="width: 100%;">
            @foreach (array_chunk($charts, 2, true) as $chunk)
                <tr>
                    @foreach ($chunk as $id => $chartImage)
                        <td class="no-border" style="width: 50%; text-align: center;">
                            <p>{{ Str::title(Str::replace('-', ' ', $id)) }}</p>
                            <div class="chart">
                                <img src="{{ $chartImage }}" alt="{{ $id }}"
                                    style="max-width:100%; height:auto;" class="text-center">
                            </div>
                        </td>
                    @endforeach
                    @if (count($chunk) < 2)
                        <td class="no-border" style="width: 50%;"></td>
                    @endif
                </tr>
            @endforeach
        </table>
    @endif
    @if ($cheques->count() > 0)
        <h2>Details</h2>
        <table>
            <thead>
                <tr>
                    @foreach ($cheques[0] as $key => $value)
                        <th>{{ $key }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach ($cheques as $c)
                    <tr>
                        @foreach ($c as $key => $value)
                            <td>{{ $value }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
        <strong>Total: </strong>{{ $cheques->count() }}
    @else
        <p>No check records found.</p>
    @endif
    @if ($claimants->count() > 0)
        <table style="margin-top: 20px;">
            <thead>
                <tr>
                    @foreach ($claimants[0] as $key => $value)
                        <td>{{ Str::title(Str::replace('_', ' ', $key)) }}</td>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach ($claimants as $cm)
                    <tr>
                        @foreach ($cm as $key => $value)
                            <td>{{ $value }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
        <strong>Total: </strong> {{ $claimants->count() }}
    @else
        <p>No claimant records found.</p>
    @endif
    <table>
        <tbody>
            <tr>
                <td class="no-border text-muted">
                    Report Generated at {{ \Carbon\Carbon::now()->toISOString() }}
                </td>
                <td class="no-border text-muted" style="text-align: right;">
                    Generated by
                    {{ auth()->user()->first_name }}
                    {{ auth()->user()->last_name }}
                </td>
            </tr>
        </tbody>
    </table>
</body>

</html>
