<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cheques Report</title>
    <style>
        body {font-size: 12px;}
        table {width: 100%; border-collapse: collapse; margin-top: 20px;}
        .text-center {text-align: center;}
        .title {font-weight: bold; font-size: 24px; text-transform: uppercase; font-family: serif;}
        .subtitle {font-size: 16px; text-transform: uppercase; font-family: serif;}
        .logo {width: 70%; height: auto;}
        .no-border {border: none !important;}
        th, td {border: 1px solid #000000; padding: 6px; text-align: left;}
        th {background-color: #f2f2f2;}
        .text-muted {color: #6c757d !important; font-size: 8px;}
    </style>
</head>
<body>
    <table>
        <tr>
            <td style="width: 30%; text-align: center;" class="no-border">
                <img src="./images/CSWDO.webp" alt="" class="logo">
            </td>
            <td class="no-border">
                <h1 class="title text-center">Taguig City CSWDO</h1>
                <p class="subtitle text-center" style="font-weight: bold;">Funeral Assistance</p>
                <h2 class="text-center" style="font-family: serif; text-transform: uppercase;">Cheques Report</h2>
                <p class="text-center" style="font-family: serif;">{{ \Carbon\Carbon::parse($startDate)->format('F d, Y') }} to {{ \Carbon\Carbon::parse($endDate)->format('F d, Y') }}</p>
            </td>
            <td style="width: 30%; text-align: center;" class="no-border">
                <img src="./images/city_logo.webp" alt="" class="logo">
            </td>
        </tr>
    </table>
    <h2>Charts</h2>
    @if(!empty($charts))
        <table class="no-border" style="width: 100%;">
            @foreach (array_chunk($charts, 2, true) as $chunk)
                <tr>
                    @foreach($chunk as $id => $chartImage)
                        <td class="no-border" style="width: 50%; text-align: center;">
                            <p>{{ Str::title(Str::replace('-', ' ', $id)) }}</p>
                            <div class="chart">
                                <img src="{{ $chartImage }}" alt="{{ $id }}" style="max-width:100%; height:auto;" class="text-center">
                            </div>
                        </td>
                    @endforeach
                    @if (count($chunk) < 2)
                        <td class="no-border" style="width: 50%;"></td>
                    @endif
                </tr>
            @endforeach
        </table>
    @endif
    <h2>Details</h2>
    <table>
        <thead>
            <tr>
                <th>Cheque Number</th>
                <th>OBR Number</th>
                <th>DV Number</th>
                <th>Amount</th>
                <th>Date Issued</th>
                <th>Date Claimed</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($cheques as $c)
                <tr>
                    <td>{{ $c->cheque_number }}</td>
                    <td>{{ $c->obr_number }}</td>
                    <td>{{ $c->dv_number }}</td>
                    <td>{{ $c->amount }}</td>
                    <td>{{ $c->date_issued }}</td>
                    <td>{{ $c->date_claimed }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <strong>Total: </strong>{{ $cheques->count() }}
    <table style="margin-top: 20px;">
        <thead>
            <tr>
                <th>Claimant</th>
                <th>Mobile Number</th>
                <th>Address</th>
                <th>Cheque Number</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($claimants as $cm)
                <tr>
                    <td>
                        {{ $cm->first_name }} 
                        {{ $cm->middle_name ? Str::limit($cm?->middle_name, 1, '.') : '' }} 
                        {{ $cm->last_name }}
                        {{ $cm->suffix ?? '' }}
                    </td>
                    <td>
                        {{ $cm->mobile_number }}
                    </td>
                    <td>
                        {{ $cm->address }}, {{ $cm->barangay->name }}
                    </td>
                    <td>
                        {{ $cm->cheque ? $cm->cheque->cheque_number : '' }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <strong>Total: </strong> {{ $claimants->count() }}
    <table>
        <tbody>
            <tr>
                <td class="no-border text-muted">
                    Report Generated at {{ \Carbon\Carbon::now()->toISOString() }}
                </td>
                <td class="no-border text-muted" style="text-align: right;">
                    Generated by 
                    {{ auth()->user()->first_name }} 
                    {{ auth()->user()->last_name }}
                </td>
            </tr>
        </tbody>
    </table>
</body>
</html>